-- MindMirror schema (PostgreSQL). Flyway owns the schema; Hibernate ddl-auto=none.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(60)  NOT NULL UNIQUE,
    email         VARCHAR(160) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(160),
    date_of_birth DATE,
    gender        VARCHAR(20),
    role          VARCHAR(20)  NOT NULL,
    age_group     INTEGER      NOT NULL,
    locale        VARCHAR(5)   NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL
);

CREATE TABLE user_stats (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT  NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    total_xp       INTEGER NOT NULL DEFAULT 0,
    level          INTEGER NOT NULL DEFAULT 1,
    current_streak INTEGER NOT NULL DEFAULT 0,
    longest_streak INTEGER NOT NULL DEFAULT 0,
    last_log_date  DATE
);

CREATE TABLE daily_logs (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    log_date              DATE        NOT NULL,
    sleep_hours           DOUBLE PRECISION NOT NULL,
    stress_level          INTEGER     NOT NULL,
    mood_score            INTEGER     NOT NULL,
    mood_emoji            VARCHAR(8),
    physical_activity_min INTEGER     NOT NULL,
    water_intake          DOUBLE PRECISION NOT NULL,
    screen_time_hours     DOUBLE PRECISION NOT NULL,
    study_hours           DOUBLE PRECISION NOT NULL,
    social_time_min       INTEGER     NOT NULL,
    energy_level          INTEGER     NOT NULL,
    nutrition_quality     INTEGER     NOT NULL,
    notes                 VARCHAR(1000),
    created_at            TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_daily_logs_user_date UNIQUE (user_id, log_date)
);
CREATE INDEX idx_daily_logs_user_date ON daily_logs(user_id, log_date);

CREATE TABLE wellness_scores (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_log_id           BIGINT      NOT NULL UNIQUE REFERENCES daily_logs(id) ON DELETE CASCADE,
    user_id                BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    log_date               DATE        NOT NULL,
    burnout_index          DOUBLE PRECISION NOT NULL,
    sleep_score            DOUBLE PRECISION NOT NULL,
    wellbeing_score        DOUBLE PRECISION NOT NULL,
    social_balance_score   DOUBLE PRECISION NOT NULL,
    productivity_score     DOUBLE PRECISION NOT NULL,
    overall_wellness_score DOUBLE PRECISION NOT NULL,
    risk_level             VARCHAR(10) NOT NULL,
    created_at             TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_wellness_user_date ON wellness_scores(user_id, log_date);

CREATE TABLE recommendations (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    daily_log_id BIGINT      REFERENCES daily_logs(id) ON DELETE CASCADE,
    log_date     DATE        NOT NULL,
    category     VARCHAR(40) NOT NULL,
    severity     VARCHAR(10) NOT NULL,
    text_en      VARCHAR(500) NOT NULL,
    text_mk      VARCHAR(500) NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_reco_user ON recommendations(user_id, created_at);

CREATE TABLE challenges (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    challenge_date DATE         NOT NULL,
    type           VARCHAR(40)  NOT NULL,
    title_en       VARCHAR(160) NOT NULL,
    title_mk       VARCHAR(160) NOT NULL,
    description_en VARCHAR(400),
    description_mk VARCHAR(400),
    xp_reward      INTEGER      NOT NULL,
    status         VARCHAR(20)  NOT NULL,
    completed_at   TIMESTAMPTZ,
    created_at     TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uk_challenge_user_date UNIQUE (user_id, challenge_date)
);

CREATE TABLE achievements (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           VARCHAR(40)  NOT NULL UNIQUE,
    title_en       VARCHAR(120) NOT NULL,
    title_mk       VARCHAR(120) NOT NULL,
    description_en VARCHAR(300),
    description_mk VARCHAR(300),
    icon           VARCHAR(40),
    xp_reward      INTEGER      NOT NULL
);

CREATE TABLE user_achievements (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT  NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    achievement_id BIGINT  NOT NULL REFERENCES achievements(id) ON DELETE CASCADE,
    progress       INTEGER NOT NULL DEFAULT 0,
    unlocked_at    TIMESTAMPTZ,
    CONSTRAINT uk_user_achievement UNIQUE (user_id, achievement_id)
);

CREATE TABLE avatar_states (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    log_date        DATE        NOT NULL,
    state           VARCHAR(20) NOT NULL,
    animation       VARCHAR(20) NOT NULL,
    attributes_json VARCHAR(1000),
    caption_en      VARCHAR(200),
    caption_mk      VARCHAR(200),
    created_at      TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_avatar_user_date ON avatar_states(user_id, log_date);

CREATE TABLE prediction_history (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    prediction_date        DATE        NOT NULL,
    for_date               DATE        NOT NULL,
    mood_tomorrow          DOUBLE PRECISION NOT NULL,
    burnout_tomorrow       DOUBLE PRECISION NOT NULL,
    stress_tomorrow        DOUBLE PRECISION NOT NULL,
    sleep_quality_tomorrow DOUBLE PRECISION NOT NULL,
    recommended_activity   VARCHAR(40),
    model_version          VARCHAR(20),
    created_at             TIMESTAMPTZ NOT NULL
);

CREATE TABLE notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type       VARCHAR(30)  NOT NULL,
    title_en   VARCHAR(160) NOT NULL,
    title_mk   VARCHAR(160) NOT NULL,
    body_en    VARCHAR(500),
    body_mk    VARCHAR(500),
    read_flag  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_notif_user ON notifications(user_id, created_at);

CREATE TABLE hbsc_reference_data (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country   VARCHAR(60) NOT NULL,
    indicator VARCHAR(60) NOT NULL,
    age_group INTEGER,
    gender    VARCHAR(10) NOT NULL,
    value     DOUBLE PRECISION NOT NULL,
    unit      VARCHAR(20) NOT NULL,
    year      INTEGER     NOT NULL,
    source    VARCHAR(300)
);
CREATE INDEX idx_hbsc_country_indicator ON hbsc_reference_data(country, indicator);
